#include "globals.h"

namespace globals {
    std::mutex espMutex;
    std::vector<ESPPlayer> espPlayers;

    bool g_espEnabled = true;
    bool g_espOnlyVis = false;
    int g_espBoxStyle = 0;
    float g_espBoxThick = 1.5f;
    float g_espEnemyCol[4]{1.f,0.25f,0.25f,1.f};
    float g_espTeamCol[4]{0.25f,0.55f,1.f,1.f};
    bool g_espShowTeam = true;
    bool g_espName = true;
    float g_espNameSize = 13.5f;
    bool g_espHealth = true;
    bool g_espHealthText = true;
    int g_espHealthPos = 0;
    int g_espHealthStyle = 0;
    float g_espHealthGradientCol1[4]{0.2f,0.92f,0.51f,1.f};
    float g_espHealthGradientCol2[4]{1.f,0.27f,0.27f,1.f};
    bool g_espDist = true;
    float g_espMaxDist = 100.f;
    bool g_espSkeleton = false;
    bool g_espBoneBox = false;
    bool g_espLines = false;
    int g_espLineAnchor = 1;
    bool g_espOof = false;
    float g_espOofSize = 24.f;
    float g_skeletonThick = 1.1f;
    bool g_espHeadDot = true;
    bool g_espSpotted = true;
    bool g_visCheckEnabled = true;
    bool g_espWeapon = true;
    bool g_espWeaponIcon = true;
    bool g_espAmmo = true;
    int g_espAmmoStyle = 0;
    float g_espAmmoCol1[4]{0.02f,0.02f,0.04f,1.f};
    float g_espAmmoCol2[4]{0.35f,0.55f,1.f,1.f};
    bool g_espAvatar = true;
    bool g_espMoney = true;
    int g_espMoneyPos = 0;
    float g_espHeadForward = 6.f;
    float g_espScale = 1.0f;
    int g_espPreviewPos = 0;
    bool g_noFlash = false;
    bool g_noSmoke = false;
    bool g_noCrosshair = false;
    bool g_noLegs = false;
    bool g_glowEnabled = false;
    float g_glowEnemyCol[4]{1.f,0.18f,0.18f,1.f};
    float g_glowTeamCol[4]{0.18f,0.5f,1.f,1.f};
    float g_glowAlpha = 1.0f;
    bool g_chamsEnabled = false;
    bool g_chamsEnemyOnly = true;
    bool g_chamsIgnoreZ = false;
    int g_chamsMaterial = 0;
    float g_chamsEnemyCol[4]{1.f,0.2f,0.2f,1.f};
    float g_chamsTeamCol[4]{0.2f,0.5f,1.f,1.f};
    float g_chamsIgnoreZCol[4]{0.4f,0.9f,0.5f,0.8f};
    bool g_chamsScene = true;
    bool g_weaponChamsEnabled = false;
    float g_weaponChamsCol[4]{1.f,0.88f,0.35f,1.f};
    bool g_aimbotEnabled = false;
    int g_aimbotKey = 1; // VK_LBUTTON
    float g_aimbotFov = 5.f;
    float g_aimbotSmooth = 6.f;
    bool g_fovCircleEnabled = false;
    float g_fovCircleCol[4]{0.4f,0.7f,1.f,0.5f};
    bool g_aimbotTeamChk = true;
    int g_aimbotWeaponFilter = 0;
    bool g_rcsEnabled = false;
    float g_rcsX = 1.0f;
    float g_rcsY = 1.0f;
    float g_rcsSmooth = 6.0f;
    bool g_tbEnabled = false;
    int g_tbKey = 0;
    int g_tbDelay = 50;
    bool g_tbTeamChk = true;
    bool g_dtEnabled = false;
    int g_dtKey = 0;
    bool g_bhopEnabled = false;
    bool g_strafeEnabled = false;
    int g_strafeKey = 0;
    bool g_antiAimEnabled = false;
    int g_antiAimType = 0;
    float g_antiAimSpeed = 180.f;
    bool g_fovEnabled = false;
    float g_fovValue = 90.f;
    bool g_autostopEnabled = false;
    bool g_snowEnabled = false;
    int g_snowDensity = 1;
    bool g_sakuraEnabled = false;
    float g_sakuraCol[4]{1.f,0.55f,0.7f,0.85f};
    bool g_starsEnabled = false;
    bool g_particlesWorld = false;
    float g_particlesWorldRadius = 600.f;
    float g_particlesWorldHeight = 320.f;
    float g_particlesWorldFloor = 40.f;
    float g_particlesWind = 18.f;
    float g_particlesDepthFade = 0.0022f;
    bool g_handsColorEnabled = false;
    float g_handsColor[4]{0.9f,0.9f,0.95f,1.f};
    bool g_skyColorEnabled = false;
    float g_skyColor[4]{0.4f,0.5f,0.8f,1.f};
    bool g_watermarkEnabled = true;
    bool g_showFpsWatermark = true;
    bool g_spectatorListEnabled = true;
    bool g_hitNotifEnabled = true;
    bool g_killNotifEnabled = true;
    bool g_hitSoundEnabled = false;
    bool g_hitmarkerEnabled = false;
    float g_hitmarkerDuration = 0.4f;
    int g_hitmarkerStyle = 0;
    bool g_killEffectEnabled = false;
    float g_killEffectDuration = 0.6f;
    int g_hitEffectType = 0;
    int g_killEffectType = 1;
    float g_hitEffectCol[4]{1.f,0.9f,0.2f,0.9f};
    float g_killEffectCol[4]{1.f,0.3f,0.3f,0.95f};
    int g_hitSoundType = 1;
    bool g_radarEnabled = true;
    bool g_radarIngame = true;
    float g_radarRange = 2000.f;
    float g_radarSize = 180.f;
    bool g_bombTimerEnabled = true;
    bool g_bulletTraceEnabled = true;
    float g_impactCol[4]{0.35f,0.94f,0.47f,0.78f};
    bool g_soundEnabled = true;
    float g_soundPuddleScale = 1.0f;
    float g_soundPuddleAlpha = 1.0f;
    bool g_soundBlipEnemy = true;
    bool g_soundBlipTeam = false;
    float g_soundBlipCol[4]{1.f, 0.f, 0.f, 1.f};
    float g_accentColor[4]{0.1f,0.55f,1.0f,1.0f};
    float g_menuOpacity = 0.96f;
    float g_uiScale = 1.00f;
    int g_menuTheme = 0;
    float g_themeTransition = 0.f;
    float g_menuAnimSpeed = 12.f;
    
    bool g_inventoryNameTagEnabled = false;
    char g_inventoryNameTag[32] = "";
    bool g_showDebugConsole = false;
    std::vector<std::string> g_debugLogs;
}
