cmake_minimum_required(VERSION 3.25)

if(NOT DEFINED LLVM_MINGW_ROOT OR LLVM_MINGW_ROOT STREQUAL "")
    set(LLVM_MINGW_ROOT "$ENV{LLVM_MINGW_ROOT}")
endif()

if(NOT LLVM_MINGW_ROOT OR LLVM_MINGW_ROOT STREQUAL "")
    message(FATAL_ERROR "Set LLVM_MINGW_ROOT to the extracted llvm-mingw directory.")
endif()

cmake_path(NORMAL_PATH LLVM_MINGW_ROOT OUTPUT_VARIABLE LLVM_MINGW_ROOT)

set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_C_COMPILER "${LLVM_MINGW_ROOT}/bin/x86_64-w64-mingw32-clang")
set(CMAKE_CXX_COMPILER "${LLVM_MINGW_ROOT}/bin/x86_64-w64-mingw32-clang++")
set(CMAKE_RC_COMPILER "${LLVM_MINGW_ROOT}/bin/llvm-windres")
set(CMAKE_AR "${LLVM_MINGW_ROOT}/bin/llvm-ar")
set(CMAKE_RANLIB "${LLVM_MINGW_ROOT}/bin/llvm-ranlib")

set(CMAKE_C_COMPILER_TARGET x86_64-w64-windows-gnu)
set(CMAKE_CXX_COMPILER_TARGET x86_64-w64-windows-gnu)

set(CMAKE_FIND_ROOT_PATH "${LLVM_MINGW_ROOT}/x86_64-w64-mingw32")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
